### ISSUE TITLE
Prompted for password on result iso in qemu

### ISSUE THREAD

**Issue by bigk-fr** [kamilion/customizer-qt5#4]
Hello,

As a former user of uck, I like customizer a lot since I started to use it a couple days ago.

I think that I found a bug, trying to remaster Xubuntu 16.04 64 bit.
I used 'customize -x' then launched firefox and added plugins to it into the nested session. that's all I did.
Then I built the iso using 'customize -r'.
When trying to boot the result iso by using 'customize -q' I was prompted for a password to boot xubuntu.

I made some investigation to find the origin of the problem.
While launching xnested chroot, customize launched startxfce4 to start xfce4 session. startxfce4 then launched pgp-agent as described in http://docs.xfce.org/xfce/xfce4-session/advanced . It created a .gnupg directory in '/etc/skel' and that's the cause of the problem. By deleting the '.gnupg' directory in '/etc/skel' in the remastered filesystem, the 'customize -r' resulting iso will boot without prompting for a password. 

Hope this could help.

**Comment by kamilion** [comment]
Hm, I can't really think of a good way to keep this from recurring on the Customizer side. 
Have you considered using a hook script? Customizer will copy it into the target for you, but from there, it's up to the script to dig around.

https://github.com/kamilion/kamikazi-core/blob/master/resources/buildscripts/xenial/autobuild.customizer.hook.sh

This might explain what I mean a bit better? It's how I use Customizer myself.
