### ISSUE TITLE
After "Request linux-signed-generic instead of linux-image-generic"

### ISSUE THREAD

**Issue by LordMrcS** [kamilion/customizer-qt5#5]
It gives error: "E: Unable to locate package linux-signed-generic" 

Tested with Ubuntu 14.04 / 15.10 / 16.04 all i386 versions.

Will test with old customizer version prior to this change and report back.

PS.: as chroot I can do sudo apt-get update and it works, and I can't find the package myself.

**Comment by LordMrcS** [comment]
Confirmed! Changed the file **src/actions/rebuild.py** from **signed to image** and it works perfectly!

**Comment by kamilion** [comment]
Ah, sorry about that, I'll add a check to make this work for 32bit; I haven't had a request for a 32bit build of kamikazi since 15.04, so it's been low on my priorities list. Good to see @clearkimura still answering the occasional question at the original.

**Comment by kamilion** [comment]
This issue (linux-signed-generic vs linux-image-generic) was fixed in some of my recent commits; this forked repo will go away and I'll take over the official one.
