### ISSUE TITLE
no work in Cinnamon/Linux Mint Cinnamon "sarah" 

### ISSUE THREAD

**Issue by mitsuzero** [kamilion/customizer-qt5#6]
![captura de pantalla de 2016-08-07 11-31-56](https://cloud.githubusercontent.com/assets/5394230/17463751/98ec94be-5c92-11e6-841e-ba799c9b8503.png)
this errors show in any button, i can't add repos, or open a "files" window... whitin the Customizer-gui.
i want to custom, this ISO - Ubuntu mini Remix 16.04, mint "sarah" is based on "16.04", i cant use any tool inside the "customizer" app... thanks in advance... and ... where to see "logs" ?? ...  @kamilion

**Comment by mitsuzero** [comment]
No one is helping right now? ..... O_o'''

**Comment by kamilion** [comment]
Sorry, for some reason I don't recall seeing a notification for this.

If you could enable debug logging, I might be able to figure out what's gone awry from the terminal output. Attaching a text file is preferable to pasting it as text in the issue, as it may be quite long.

**Comment by kamilion** [comment]
I might have just fixed this by applying #7 
Well, I mean, the error message will display now instead of a blank window (sorry about that!)
